DROP DATABASE IF EXISTS exo_contacts;
CREATE DATABASE IF NOT EXISTS exo_contacts;
USE exo_contacts;

CREATE TABLE IF NOT EXISTS pays (
    iso_3 VARCHAR(3) PRIMARY KEY,
    nom VARCHAR(70) NOT NULL,
    iso_2 VARCHAR(2) NOT NULL,
    nationalite VARCHAR(50) NOT NULL
);